// Generated by https://quicktype.io

export interface CartItem {
    quantity:    number;
    seller:      string;
    id:          string;
    attachments?: Attachment[];
}

export interface Attachment {
    name:    string;
    content: any;
}
