// Generated by https://quicktype.io

export interface ProductInfoRequest {
    productid:             string;
    quantity:              number;
    selectedattributes:    any[] | any;
    zakekeprice:           number;
    zakekepercentageprice: number;
    additionaldata:        any;
}

